Applicação/TePeCe/config/routes.rb
Rails.application.routes.draw do

  resources :turmas do
    get 'statistics'
    collection do
      get 'statistics_index'
    end
  end

  resources :disciplinas

  resources :exercicios do
    resources :resolucaos
    resources :nota
    collection do
      get 'bydisc/:disciplina_id' => 'exercicios#bydisc', :as => "bydisc"
    end
  end

  resources :encarregados

  resources :profs

  resources :alunos do
    get 'statistics'
    collection do
      get 'statistics_index'
      get 'statistics_index/byturma/:turma_id' => 'alunos#stats_byturma', :as => "stats_byturma"
      get 'byturma/:turma_id' => 'alunos#byturma', :as => "byturma"
    end
  end

  resources :direcs

	resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/statistics'

  resources :users do
    resources :mensagens
  end

  root 'static_pages#home'
  
	match '/signup',  to: 'users#new',            via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

end

Applicação/TePeCe/app/models/aluno.rb
class Aluno < ActiveRecord::Base
	belongs_to :user
	has_many :exercios
	has_many :notas
	belongs_to :turma
	belongs_to :encarregado
	
	
	
end

Applicação/TePeCe/app/models/direc.rb
class Direc < ActiveRecord::Base
end

Applicação/TePeCe/app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
	has_many :exercicios
end

Applicação/TePeCe/app/models/encarregado.rb
class Encarregado < ActiveRecord::Base
	has_many :alunos
end

Applicação/TePeCe/app/models/exercicio.rb
class Exercicio < ActiveRecord::Base
	belongs_to :aluno
	has_one :resolucao
	has_one :nota
	has_one :disciplina
	belongs_to :prof
end

Applicação/TePeCe/app/models/mensagen.rb
class Mensagen < ActiveRecord::Base
	belongs_to :destino, class_name: 'User', foreign_key: 'destinatario'
	belongs_to :origem, class_name: 'User', foreign_key: 'remetente'
end

Applicação/TePeCe/app/models/nota.rb
class Nota < ActiveRecord::Base
	belongs_to :exercicio
	belongs_to :aluno
end

Applicação/TePeCe/app/models/prof.rb
class Prof < ActiveRecord::Base
	has_many :exercicios
end

Applicação/TePeCe/app/models/resolucao.rb
class Resolucao < ActiveRecord::Base
	belongs_to :exercicio
end

Applicação/TePeCe/app/models/turma.rb
class Turma < ActiveRecord::Base
	has_many :alunos
end

Applicação/TePeCe/app/models/user.rb
class User < ActiveRecord::Base
	has_one :aluno, dependent: :destroy
	has_one :prof
	has_one :direc
	has_one :encarregado
	
	has_many :mensagens
	
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
				format: { with: VALID_EMAIL_REGEX },
				length: { maximum: 50 },
				uniqueness: true
	has_secure_password			
	validates :password, length: { minimum: 6 }
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	
	def user_name
		if self.aluno
			self.aluno.nome
		elsif self.prof
			self.prof.nome
		elsif self.direc
			self.direc.nome
		else
			self.encarregado.nome
		end	
	end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
	
end

Applicação/TePeCe/app/controllers/exercicios_controller.rb
class ExerciciosController < ApplicationController
  before_action :set_exercicio, only: [:show, :edit, :update, :destroy]

  # GET /exercicios
  # GET /exercicios.json
  def index
    if current_user.aluno
      @exercicios = Exercicio.where(:aluno_id => current_user.aluno)
    elsif current_user.encarregado
      filhos = Aluno.where(:encarregado_id => current_user.encarregado).select(:id)
      @exercicios = Exercicio.where("aluno_id in (?)",  filhos)
    elsif current_user.prof
      @exercicios = Exercicio.where(:prof_id => current_user.prof)
    else
      @exercicios = Exercicio.all
    end
  end

  # GET /exercicios/1
  # GET /exercicios/1.json
  def show
  end

  # GET /exercicios/new
  def new
    @exercicio = Exercicio.new
  	@alunos = Aluno.all
    @disciplinas = Disciplina.all
    @exercicio.disciplina_id = params[:format]
    @exercicio.prof_id = current_user.prof.id
  end

  # GET /exercicios/1/edit
  def edit
    @alunos = Aluno.all
    @disciplinas = Disciplina.all
    @exercicio.prof_id = current_user.prof.id
  end

  # POST /exercicios
  # POST /exercicios.json
  def create
    @exercicio = Exercicio.new(exercicio_params)
    @exercicio.prof_id = current_user.prof.id

    respond_to do |format|
      if @exercicio.save and @exercicio.save
        format.html { redirect_to @exercicio, notice: 'Exercicio was successfully created.' }
        format.json { render :show, status: :created, location: @exercicio }
      else
        format.html { render :new }
        format.json { render json: @exercicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercicios/1
  # PATCH/PUT /exercicios/1.json
  def update
    respond_to do |format|
      if @exercicio.update(exercicio_params)
        format.html { redirect_to @exercicio, notice: 'Exercicio was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercicio }
      else
        format.html { render :edit }
        format.json { render json: @exercicio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercicios/1
  # DELETE /exercicios/1.json
  def destroy
    @exercicio.destroy
    respond_to do |format|
      format.html { redirect_to exercicios_url, notice: 'Exercicio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def bydisc
    excs = Exercicio.where(:disciplina_id => params[:disciplina_id])
    @disciplina = Disciplina.find(params[:disciplina_id])
    if current_user.aluno
      @exercicios = excs.where(:aluno_id => current_user.aluno)
    elsif current_user.encarregado
      filhos = Aluno.where(:encarregado_id => current_user.encarregado).select(:id)
      @exercicios = excs.where("aluno_id in (?)",  filhos)
    elsif current_user.prof
      @exercicios = excs.where(:prof_id => current_user.prof)
    else
      @exercicios = excs.all
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercicio
      @exercicio = Exercicio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercicio_params
      params.require(:exercicio).permit(:titulo, :enunciado, :aluno_id, :disciplina_id)
    end
end

Applicação/TePeCe/app/helpers/alunos_helper.rb
module AlunosHelper
end

Applicação/TePeCe/app/helpers/application_helper.rb
module ApplicationHelper
end

Applicação/TePeCe/app/helpers/direcs_helper.rb
module DirecsHelper
end

Applicação/TePeCe/app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

Applicação/TePeCe/app/helpers/mensagens_helper.rb
module MensagensHelper
end

Applicação/TePeCe/app/helpers/nota_helper.rb
module NotaHelper
end

Applicação/TePeCe/app/helpers/profs_helper.rb
module ProfsHelper
end

Applicação/TePeCe/app/helpers/resolucaos_helper.rb
module ResolucaosHelper
end

Applicação/TePeCe/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end
	
	def sign_out
		current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

Applicação/TePeCe/app/helpers/turmas_helper.rb
module TurmasHelper
end

Applicação/TePeCe/app/helpers/users_helper.rb
module UsersHelper
end

Applicação/TePeCe/app/views/exercicios/_form.html.erb
<%= form_for(@exercicio) do |f| %>
  <% if @exercicio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercicio.errors.count, "error") %> prohibited this exercicio from being saved:</h2>

      <ul>
      <% @exercicio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">
	<div class="span3 offset1">  
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :enunciado %><br>
    <%= f.text_area :enunciado,  placeholder: "Novo Exercicio..." %>
  </div>
  <div class="field">
    <%= f.label :aluno_id %><br>
	<%= f.collection_select :aluno_id, @alunos, :id, :nome %>
  </div>
  <div class="field">
    <%= f.label :disciplina_id %><br>
  <%= f.collection_select :disciplina_id, @disciplinas, :id, :designacao %>
  </div>
  <div class="actions">
    <%= f.submit "Gravar", class: "btn btn-primary"%>
  </div>
  </div>
  </div>
<% end %>

Applicação/TePeCe/app/views/exercicios/bydisc.html.erb
<h1></h1>

<% if current_user.prof %>
  <%= link_to image_tag("add-database-icon.png") + 'Novo exercicio', new_exercicio_path(@disciplina) %>
<% end %>

<br><br>
<legend>Exercicios de <%= @disciplina.designacao %></legend>

<div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                  <th>Titulo</th>
						                    <% if not current_user.prof %>
												<th>Professor</th>
											<% end %>
						                  
										  <% if not current_user.aluno %>
											<th>Aluno</th>
											<% end %>			
						                  <th>Resolvido</th>
										  <th>Nota</th>
						                </tr>
						              </thead>
						              
									  
									  
									  <tbody>
									   <% @exercicios.each do |exercicio| %>
						                <tr>
						                         <td><%= exercicio.titulo %></td>
												<% if not current_user.prof %>
												 <td><%= Prof.find(exercicio.prof_id).nome %></td>
												<% end %>
												<% if not current_user.aluno %>
												  <td><%= Aluno.find(exercicio.aluno_id).nome %></td>
												<% end %>
												<% if exercicio.resolucao %>
												  <td>Sim</td>
												<% else %>
												  <td>Nao</td>
												<% end %>
												<% if exercicio.nota %>
												  <td><%= exercicio.nota.valor %></td>
												<% else %>
												  <td>N/A</td>
												<% end %>
												<td><%= link_to image_tag("search-icon24.png") + 'Ver', exercicio %></td>
										<% if current_user.prof %>
												<td><%= link_to image_tag("edit-icon24.png") +'Editar', edit_exercicio_path(exercicio) %></td>
												<td><%= link_to image_tag("delete-icon24.png") +'Retirar', exercicio, method: :delete, data: { confirm: 'Tem acerteza que quer retirar este exercicio?' } %></td>
										<% end %>
						                  
										 
										</tr>
										 <% end %>
						              </tbody>
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>




<br>



<%= link_to 'Voltar', disciplinas_path %>

Applicação/TePeCe/app/views/exercicios/edit.html.erb
<h1></h1>
<legend>Editar exercicio</legend>

<%= render 'form' %>

<%= link_to 'Ver', @exercicio %> |
<%= link_to 'Voltar', exercicios_path %>

Applicação/TePeCe/app/views/exercicios/index.html.erb
<h1></h1>
<% if current_user.prof %>
  <%= link_to image_tag("add-database-icon.png") + 'Novo exercicio', new_exercicio_path %>
<% end %>
<br>
<br>

<legend>Lista de Exercicios</legend>

<div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                 <th>Titulo</th>
										  <th>Disciplina</th>
										  <% if not current_user.prof %>
											<th>Professor</th>
										  <% end %>
										  <% if not current_user.aluno %>
											<th>Aluno</th>
										  <% end %>
										  <th>Resolvido</th>
										  <th>Nota</th>
										  <th colspan="5"></th>
						                </tr>
						              </thead>
									  
									      <% @exercicios.each do |exercicio| %>
											  <tr>
												<td><%= exercicio.titulo %></td>
												<td><%= link_to Disciplina.find(exercicio.disciplina_id).designacao, bydisc_exercicios_path(exercicio.disciplina_id) %></td>
												<% if not current_user.prof %>
												  <td><%= Prof.find(exercicio.prof_id).nome %></td>
												<% end %>
												<% if not current_user.aluno %>
												  <td><%= Aluno.find(exercicio.aluno_id).nome %></td>
												<% end %>
												<% if exercicio.resolucao %>
												  <td>Sim</td>
												<% else %>
												  <td>Nao</td>
												<% end %>
												<% if exercicio.nota %>
												  <td><%= exercicio.nota.valor %></td>
												<% else %>
												  <td>N/A</td>
												<% end %>
												<td><%= link_to image_tag("search-icon24.png") + 'Ver', exercicio %></td>
										<% if current_user.prof %>
												<td> <%= link_to image_tag("edit-icon24.png") + 'Editar', edit_exercicio_path(exercicio) %></td>
												<td> <%= link_to image_tag("delete-icon24.png")+'Retirar', exercicio, method: :delete, data: { confirm: 'Tem acerteza que quer retirar este exercicio?' } %></td>
										<% end %>
											  </tr>
											<% end %>
						              
									  
									
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>

<br>


<%= link_to 'Voltar', disciplinas_path %>

Applicação/TePeCe/app/views/exercicios/new.html.erb
<h1></h1>
<legend>Novo exercicio</legend>

<%= render 'form' %>

<%= link_to 'Voltar', exercicios_path %>

Applicação/TePeCe/app/views/exercicios/show.html.erb
<h1></h1>
<legend>Exercicio</legend>

<div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                  <th>#</th>
						                  <th></th>
						                  <th></th>
						                  <th></th>
						                </tr>
						              </thead>
						             
									  
									  <tbody>
						                <tr>
						                  <td></td>
						                  <td><strong>Titulo</strong></strong></td>			                  
										  <td><%= @exercicio.titulo %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Enunciado</strong></td>			                  
										  <td><%= @exercicio.enunciado %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Disciplina</strong></td>			                  
										  <td><%= Disciplina.find(@exercicio.disciplina_id).designacao %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Professor</strong></td>			                  
										  <td><%= Prof.find(@exercicio.prof_id).nome %></td>
										</tr>
										
										<tr>
										
						                  <td></td>
						                  <td><strong>Resolução</strong></td>			                  
										  <td> <% if @exercicio.resolucao != nil %>
													<%= @exercicio.resolucao.resposta  %>
												<% else %>
													<p><strong>Exercicio nao resolvido</strong></p>
												<% end %></td>
										</tr>
										
										<tr>
						                  <td></td>
										  <td><p><strong>Nota</strong></td>
						                  <td><% if @exercicio.nota != nil %>
													<%= @exercicio.nota.valor %></p>
												<% else %>
													<p><strong>Nota nao atribuida</strong></p>
												<% end %></td>			                  
										  <td><%=  %></td>
										</tr>
										
													
										
											
										<tr>
										  <td></td>
						                  <td> <br> <br>
											<% if current_user.aluno %>
												<% if not @exercicio.nota %>
													<% if @exercicio.resolucao != nil %>
														<%= link_to 'Alterar Resolucao', edit_exercicio_resolucao_path(@exercicio, @exercicio.resolucao) %> |
													<% else %>
														<%= link_to 'Resolver', new_exercicio_resolucao_path(@exercicio) %> |
													<% end %>
												<% end %>
											<% elsif current_user.prof %>
												<%= link_to image_tag("edit-icon24.png") + 'Alterar', edit_exercicio_path(@exercicio) %>
												<% if @exercicio.resolucao %>
													<% if @exercicio.nota %>
														<%= link_to  image_tag("edit-icon24.png") + 'Alterar Nota', edit_exercicio_notum_path(@exercicio, @exercicio.nota) %>
													<% else %>
														<%= link_to image_tag("edit-icon24.png") + 'Atribuir Nota', new_exercicio_notum_path(@exercicio) %>
													<% end %>
												<% end %>
											<% end %>						               		                  
										  <td> <br> <br>
										  <%= link_to image_tag("back-icon32.png") + "Voltar", alunos_path  %></td>
										</tr>		
										 
						              </tbody>
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>