Applicação/TePeCe/config/routes.rb
Rails.application.routes.draw do

  resources :turmas do
    get 'statistics'
    collection do
      get 'statistics_index'
    end
  end

  resources :disciplinas

  resources :exercicios do
    resources :resolucaos
    resources :nota
    collection do
      get 'bydisc/:disciplina_id' => 'exercicios#bydisc', :as => "bydisc"
    end
  end

  resources :encarregados

  resources :profs

  resources :alunos do
    get 'statistics'
    collection do
      get 'statistics_index'
      get 'statistics_index/byturma/:turma_id' => 'alunos#stats_byturma', :as => "stats_byturma"
      get 'byturma/:turma_id' => 'alunos#byturma', :as => "byturma"
    end
  end

  resources :direcs

	resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/statistics'

  resources :users do
    resources :mensagens
  end

  root 'static_pages#home'
  
	match '/signup',  to: 'users#new',            via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

end

Applicação/TePeCe/app/models/aluno.rb
class Aluno < ActiveRecord::Base
	belongs_to :user
	has_many :exercios
	has_many :notas
	belongs_to :turma
	belongs_to :encarregado
	
	
	
end

Applicação/TePeCe/app/models/direc.rb
class Direc < ActiveRecord::Base
end

Applicação/TePeCe/app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
	has_many :exercicios
end

Applicação/TePeCe/app/models/encarregado.rb
class Encarregado < ActiveRecord::Base
	has_many :alunos
end

Applicação/TePeCe/app/models/exercicio.rb
class Exercicio < ActiveRecord::Base
	belongs_to :aluno
	has_one :resolucao
	has_one :nota
	has_one :disciplina
	belongs_to :prof
end

Applicação/TePeCe/app/models/mensagen.rb
class Mensagen < ActiveRecord::Base
	belongs_to :destino, class_name: 'User', foreign_key: 'destinatario'
	belongs_to :origem, class_name: 'User', foreign_key: 'remetente'
end

Applicação/TePeCe/app/models/nota.rb
class Nota < ActiveRecord::Base
	belongs_to :exercicio
	belongs_to :aluno
end

Applicação/TePeCe/app/models/prof.rb
class Prof < ActiveRecord::Base
	has_many :exercicios
end

Applicação/TePeCe/app/models/resolucao.rb
class Resolucao < ActiveRecord::Base
	belongs_to :exercicio
end

Applicação/TePeCe/app/models/turma.rb
class Turma < ActiveRecord::Base
	has_many :alunos
end

Applicação/TePeCe/app/models/user.rb
class User < ActiveRecord::Base
	has_one :aluno, dependent: :destroy
	has_one :prof
	has_one :direc
	has_one :encarregado
	
	has_many :mensagens
	
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
				format: { with: VALID_EMAIL_REGEX },
				length: { maximum: 50 },
				uniqueness: true
	has_secure_password			
	validates :password, length: { minimum: 6 }
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	
	def user_name
		if self.aluno
			self.aluno.nome
		elsif self.prof
			self.prof.nome
		elsif self.direc
			self.direc.nome
		else
			self.encarregado.nome
		end	
	end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
	
end

Applicação/TePeCe/app/helpers/alunos_helper.rb
module AlunosHelper
end

Applicação/TePeCe/app/helpers/direcs_helper.rb
module DirecsHelper
end

Applicação/TePeCe/app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

Applicação/TePeCe/app/helpers/mensagens_helper.rb
module MensagensHelper
end

Applicação/TePeCe/app/helpers/nota_helper.rb
module NotaHelper
end

Applicação/TePeCe/app/helpers/profs_helper.rb
module ProfsHelper
end

Applicação/TePeCe/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end
	
	def sign_out
		current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

Applicação/TePeCe/app/helpers/turmas_helper.rb
module TurmasHelper
end

Applicação/TePeCe/app/helpers/users_helper.rb
module UsersHelper
end

Applicação/TePeCe/app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
          <nav>
             <ul>
				<li><%= link_to "Contactos", static_pages_contact_path %></li>
				<li><%= link_to "Sobre", static_pages_about_path %></li>
			</ul>
          </nav>
    </div>
</footer>

Applicação/TePeCe/app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
		<% if signed_in? %>
          <%= link_to "TePeCe", current_user, id: "logo" %>
        <% else %>
          <%= link_to "TePeCe", static_pages_home_path, id: "logo" %>
        <% end %>
          <nav>
            <ul class="nav pull-right">
			
				<% if signed_in? %>
						
				<li><%= link_to "Home", current_user %></li>
				<li id="fat-menu" class="dropdown">
					<a href=mensagens_path class="dropdown-toggle" data-toggle="dropdown">
						<%= current_user.user_name %> <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "Editar Perfil", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li>
							<%= link_to "Sair", signout_path, method: "delete" %>
						</li>
					</ul>
				</li>
				<% else %>
					<li><%= link_to "Home", static_pages_home_path %></li>
					<li><%= link_to "Entrar", signin_path %></li>
				<% end %>	
            </ul>
          </nav>
        </div>
      </div>
    </header>

Applicação/TePeCe/app/views/layouts/_menulat.html.erb
<% if signed_in? %>
<div  id="sidebar-wrapper">	
<ul class="sidebar-nav">				
	

	<li>
			<a> ...................</a>	
	</li>
	<% if not current_user.aluno %>	
		<li id="fat-menu" class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Estatisticas <b class="caret"></b>
			</a>
			<ul class="dropdown-menu">
				<% if current_user.direc %>
					<li><%= link_to "Gerais", static_pages_statistics_path %></li>
				<% end %>
				<% if not current_user.encarregado %>
					<li><%= link_to "Turmas", statistics_index_turmas_path %></li>
				<% end %>
				<li><%= link_to "Alunos", statistics_index_alunos_path %></li>
			</ul>
		</li>
	<% else %>

	<li id="fat-menu" class="dropdown">
			<li><%= link_to "Disciplinas", disciplinas_path %></li>
		</li>
		<%end%>
	
	

	<% if not current_user.direc %>			
	<li id="fat-menu" class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			Exercicio <b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			
			<% if current_user.prof %>	
			<li><%= link_to "Lancar Exercicio", new_exercicio_path %></li>
			<%end%>
			
			<li><%= link_to "Ver Exercicios", exercicios_path%></li>
		</ul>
	</li>		
	<%end%>
	
	<% if not current_user.aluno %>	
	<li id="fat-menu" class="dropdown">
		<%= link_to "Mensagens", user_mensagens_path(current_user) %>
	</li>
	<%end %>
							
	<% if current_user.direc or current_user.prof %>
		<li id="fat-menu" class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">
				Utilizadores <b class="caret"></b>
			</a>
			<ul class="dropdown-menu">
				<li><%= link_to "Alunos", alunos_path %></li>
				<li><%= link_to "Enc.Educacao", encarregados_path%></li>
				<li><%= link_to "Professores", profs_path %></li>
				<li><%= link_to "Direcao", direcs_path %></li>	
			</ul>
		</li>
		<li id="fat-menu" class="dropdown">
			<li><%= link_to "Disciplinas", disciplinas_path %></li>
		</li>
		
		<li id="fat-menu" class="dropdown">
			<li><%= link_to "Turmas", turmas_path %></li>
			
		</li>
	<% end %>
	
	<li>
			<a> ...................</a>	
	</li>
	
	</ul>
	</ul>

</div>	
	
	
<% end %>

Applicação/TePeCe/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

Applicação/TePeCe/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TePeCe</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
   <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	
	<div class="container">
      
	  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
	  
	  <div class="container">
		<div class="row">
	 
		<% if signed_in? %>	
		<div class="col-md-2">
	  		<%= render 'layouts/menulat' %>
		</div>
		
		<div class="col-md-10">
			<%= yield %>
		</div>
		
		<% else %>
			<div class="col-md-12">
				<%= yield %>
			</div>
		<% end %>
				
		
	  
	  </div>
	  </div>
	  <%= render 'layouts/footer' %>
	  
    </div>
	
</body>
</html>