Applicação/TePeCe/config/routes.rb
Rails.application.routes.draw do

  resources :turmas do
    get 'statistics'
    collection do
      get 'statistics_index'
    end
  end

  resources :disciplinas

  resources :exercicios do
    resources :resolucaos
    resources :nota
    collection do
      get 'bydisc/:disciplina_id' => 'exercicios#bydisc', :as => "bydisc"
    end
  end

  resources :encarregados

  resources :profs

  resources :alunos do
    get 'statistics'
    collection do
      get 'statistics_index'
      get 'statistics_index/byturma/:turma_id' => 'alunos#stats_byturma', :as => "stats_byturma"
      get 'byturma/:turma_id' => 'alunos#byturma', :as => "byturma"
    end
  end

  resources :direcs

	resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/statistics'

  resources :users do
    resources :mensagens
  end

  root 'static_pages#home'
  
	match '/signup',  to: 'users#new',            via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

end

Applicação/TePeCe/app/models/aluno.rb
class Aluno < ActiveRecord::Base
	belongs_to :user
	has_many :exercios
	has_many :notas
	belongs_to :turma
	belongs_to :encarregado
	
	
	
end

Applicação/TePeCe/app/controllers/alunos_controller.rb
class AlunosController < ApplicationController
  before_action :set_aluno, only: [:show, :edit, :update, :destroy]
  

  # GET /alunos
  # GET /alunos.json
  def index
   #@alunos = Aluno.all
	@alunos = Aluno.paginate(page: params[:page])
  end

  # GET /alunos/1
  # GET /alunos/1.json
  def show
  	@aluno = Aluno.find(params[:id])
    @encarregado = Encarregado.find(@aluno.encarregado_id)
    @turma = Turma.find(@aluno.turma_id)
  end

  # GET /alunos/new
  def new
    @aluno = Aluno.new
  	@user = User.new
    @encarregados = Encarregado.all
    @turmas = Turma.all
    @aluno.turma_id = params[:format]
  end

  # GET /alunos/1/edit
  def edit
  	@user = User.find(@aluno.user_id)
    @encarregados = Encarregado.all
    @turmas = Turma.all
  end

  # POST /alunos
  # POST /alunos.json
  def create
    @aluno = Aluno.new(aluno_params)
	@user = User.new(user_params)

    respond_to do |format|
      if @user.save
		@aluno.user_id = @user.id;
		if @aluno.save
			format.html { redirect_to @aluno, notice: 'Aluno criado com sucesso.' }
			format.json { render :show, status: :created, location: @aluno }
		end
	else
        format.html { render :new }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
    end
   end
  end

  # PATCH/PUT /alunos/1
  # PATCH/PUT /alunos/1.json
  def update
	@user = User.find(@aluno.user_id)
	
	respond_to do |format|
      if @aluno.update(aluno_params) and @user.update(user_params)
        format.html { redirect_to @aluno, notice: 'Aluno atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @aluno }
      else
        format.html { render :edit }
        format.json { render json: @aluno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alunos/1
  # DELETE /alunos/1.json
  def destroy
    @user = User.find(@aluno.user_id)
    if @aluno.destroy
  		@user.destroy
      respond_to do |format|
        format.html { redirect_to alunos_url, notice: 'Aluno apagado com sucesso.' }
        format.json { head :no_content }
      end
  	end
  end

  def statistics
    @aluno = Aluno.find(params[:aluno_id])
    @user = User.find(@aluno.user_id)
    notas = Nota.where(:aluno_id => @aluno)
    @media = notas.average(:valor)
    if not @media
      @media = "N/A"
    end
    @max = notas.maximum(:valor)
    if not @max
      @max = "N/A"
    end
    @min = notas.minimum(:valor)
    if not @min
      @min = "N/A"
    end
    @poss = notas.where("valor >= ?", 10).count()
    if not @poss
      @poss = "N/A"
    end
    @negs = notas.where("valor < ?", 10).count()
    if not @negs
      @negs = "N/A"
    end
    @cmp = notas.count()
    if not @cmp
      @cmp = "N/A"
    end
    @inc = Exercicio.all.count() - @cmp
    if not @inc
      @inc = "N/A"
    end

    melhor = 0
    nomeM = "N/A"
    pior = 20
    nomeP = "N/A"

    Disciplina.all.each do |disc|
      excs = Exercicio.where(:disciplina_id => disc.id).select(:id)
      nota = Nota.where("exercicio_id in (?)", excs).average(:valor)
      if nota
        if(nota > melhor)
          melhor = nota
          nomeM = disc.designacao
        end
        if(nota < pior)
          pior = nota
          nomeP = disc.designacao
        end
      end
    end

    @best = nomeM + " (" + melhor.to_s + ")"
    if @best.include? "N/A"
      @best = "N/A"
    end
    @worst = nomeP + " (" + pior.to_s + ")"
    if @worst.include? "N/A"
      @worst = "N/A"
    end
  end

  def statistics_index
    if current_user.encarregado
      @alunos = Aluno.where(:encarregado_id => current_user.encarregado).paginate(page: params[:page])
    else
      @alunos = Aluno.paginate(page: params[:page])
    end
  end

  def byturma
    @alunos = Aluno.where(:turma_id => params[:turma_id]).paginate(page: params[:page])
    @turma = Turma.find(params[:turma_id])
  end

  def stats_byturma
    alns = Aluno.where(:turma_id => params[:turma_id]).paginate(page: params[:page])
    @turma = Turma.find(params[:turma_id])
    if current_user.encarregado
      @alunos = alns.where(:encarregado_id => current_user.encarregado).paginate(page: params[:page])
    else
      @alunos = alns.paginate(page: params[:page])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aluno
      @aluno = Aluno.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aluno_params
      params.require(:aluno).permit(:nome, :dataNasc, :nBI, :morada, :cp, :localidade, :email, :user_id, :encarregado_id, :turma_id)
    end
	
	def user_params
      params.require(:aluno).permit(:email, :password,
                                   :password_confirmation)
    end
end

Applicação/TePeCe/app/helpers/alunos_helper.rb
module AlunosHelper
end

Applicação/TePeCe/app/views/alunos/_form.html.erb
<%= form_for(@aluno) do |f| %>
  <% if @aluno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@aluno.errors.count, "error") %> prohibited this aluno from being saved:</h2>

      <ul>
      <% @aluno.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="row">
  <div class="span3 offset1">
    
	<div class="field">
	<%= f.label :nome %>
    <%= f.text_field :nome %>
	</div>

  <div class="field">
    <%= f.label :encarregado_id %><br>
	<%= f.collection_select :encarregado_id, @encarregados, :id, :nome %>
  </div>

	<div class="field">
    <%= f.label :dataNasc %>
    <%= f.date_select :dataNasc %>
	</div>
 
	<div class="field">
    <%= f.label :nBI, "Nº BI/CC:" %>
    <%= f.number_field :nBI %>
	</div>
 
	<div class="field">
    <%= f.label :morada %>
    <%= f.text_field :morada %>
	</div>
  
	<div class="field">
    <%= f.label :cp, "Cod. Postal:" %>
    <%= f.text_field :cp %>
	</div>

	<div class="field">
    <%= f.label :localidade %>
    <%= f.text_field :localidade %>
	</div>

	 <div class="field">
	<%= f.label :email %>
    <%= f.text_field :email %>
	</div>

	<div class="field">
     <%= f.label :password %>
     <%= f.password_field :password %>
	 </div>

	 <div class="field">
     <%= f.label :password_confirmation, "Confirmation" %>
     <%= f.password_field :password_confirmation %>
	 </div>
	
  <div class="field">
    <%= f.label :turma_id %><br>
  <%= f.collection_select :turma_id, @turmas, :id, :designacao %>
  </div>

	<div class="field">
		<div class="actions">
			<%= f.submit "Gravar", class: "btn btn-primary" %>
		</div>
	</div>		
		
	</div>
</div>
<% end %>

Applicação/TePeCe/app/views/alunos/byturma.html.erb
<% provide(:title, 'All users') %>
<h1></h1>

  <div>
	<br>
	<% if current_user.direc %>
      <%= link_to image_tag("add-database-icon.png") + "Adicionar Aluno", new_aluno_path  %>
    <% end %>
	  <br><br> <br>
  </div>



<legend>Alunos da turma <%= @turma.designacao %></legend>


<%= will_paginate %>

<div class="span9" id="content">
					<div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table" border="0">
						              <thead>									
										<tr>
						                  <th>#</th>
						                  <th>Nome</th>
						                  <th></th>
						                  <th></th>
						                </tr>
						              </thead>
						              
									  
									  
									  <tbody>
									   <% @alunos.each do |aluno| %>
						                <tr>
						                  <td><%= aluno.id %></td>
						                  <td><b><%= link_to aluno.nome, aluno %></b></td>
						                  
										  <% if current_user.direc %>
										  <td><%= link_to image_tag("edit-icon24.png") +'Editar', edit_aluno_path(aluno) %></td>
						                  
										  <% if current_user.admin? %>
										  <td><%= link_to image_tag("delete-icon24.png") + 'Apagar', aluno, method: :delete, data: { confirm: 'Quer apagar esta turma?' } %></td>
										  <% end %>
										  <% end %>
										</tr>
										 <% end %>
						              </tbody>
									  
									  
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
</div>


<%= will_paginate %>

<div class="links">
	<br>
	<h5>
		<%= link_to image_tag("back-icon32.png") + " Voltar", turmas_path %>
	</h5>
</div>

Applicação/TePeCe/app/views/alunos/edit.html.erb
<h1></h1>
<legend>Editar Alunos</legend>

<%= render 'form' %>

<br>
<br>
<div class="links">
	<h5>
	<%= link_to image_tag("back-icon32.png") + "Voltar", alunos_path  %>
	<h5>
</div>

Applicação/TePeCe/app/views/alunos/index.html.erb
<h1></h1>
<% if current_user.direc %>
<div class="lists">
<br>
	<%= link_to image_tag("add-database-icon.png") + "Novo Aluno", new_aluno_path  %>
<br><br><br><br>
</div>
<% end %>

<legend>Lista de Alunos</legend>


<%= will_paginate %>

<div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                  <th>#</th>
						                  <th>Nome</th>
						                  <th></th>
						                  <th></th>
						                </tr>
						              </thead>
						              
									  
									  
									  <tbody>
									   <% @alunos.each do |aluno| %>
						                <tr>
						                  <td><%= aluno.id %></td>
						                  <td><%= link_to aluno.nome, aluno %></td>
						                  
										  <% if current_user.direc %>
										  <td><%= link_to image_tag("edit-icon24.png") +'Editar', edit_aluno_path(aluno) %></td>
						                  
										  <% if current_user.admin? %>
										  <td><%= link_to image_tag("delete-icon24.png") + 'Apagar', aluno, method: :delete, data: { confirm: 'Quer apagar esta turma?' } %></td>
										  <% end %>
										  <% end %>
										</tr>
										 <% end %>
						              </tbody>
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>


<%= will_paginate %>

Applicação/TePeCe/app/views/alunos/new.html.erb
<h1></h1>
<legend>Inserir Aluno</legend>

<%= render 'form' %>

<br>
<br>
<div class="links">
	<h5>
		<%= link_to image_tag("back-icon32.png") + "Voltar", alunos_path  %>
	<h5>
</div>

Applicação/TePeCe/app/views/alunos/show.html.erb
<h1></h1>
<legend>Dados do Aluno <b><%= @aluno.nome %> </b></legend>

  <br>

  <div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                  <th>#</th>
						                  <th></th>
						                  <th></th>
						                  <th></th>
						                </tr>
						              </thead>
						             
									  
									  <tbody>
						                <tr>
						                  <td></td>
						                  <td><strong>Nome</strong></strong></td>			                  
										  <td><%= @aluno.nome %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Encarregado</strong></td>			                  
										  <td><%= @encarregado.nome %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Data Nasc</strong></td>			                  
										  <td><%= @aluno.dataNasc %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Nº Bi/CC</strong></td>			                  
										  <td><%= @aluno.nBI %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Morada</strong></td>			                  
										  <td><%= @aluno.morada %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Cód.Postal</strong></td>			                  
										  <td><%= @aluno.cp %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Email</strong></td>			                  
										  <td><%= @aluno.email %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td><strong>Turma</strong></td>			                  
										  <td><%= @turma.designacao %></td>
										</tr>
										
										<tr>
										   <td></td>
						                  <td><strong>Nº de utilizador</strong></td>						               		                  
										  <td><%= @aluno.user_id %></td>
										</tr>
											
										<tr>
										   <td></td>
						                  <td> <br> <br>
										  <% if current_user.direc %>
												<%= link_to image_tag("edit-icon24.png") + "Editar Aluno", edit_aluno_path(@aluno)  %>
												<% end %></td>						               		                  
										  <td> <br> <br>
										  <%= link_to image_tag("back-icon32.png") + "Voltar", alunos_path  %></td>
										</tr>		
										 
						              </tbody>
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>

Applicação/TePeCe/app/views/alunos/statistics.html.erb
<h1></h1>
<legend>Estatisticas do Aluno <b><%= @aluno.nome %></b></legend>

<br><br>
  <div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                  <th>#</th>
						                  <th>Descrição</th>
						                  <th>Resultado</th>
						                  <th></th>
						                </tr>
						              </thead>
						             
									  
									  									
										<tr>
						                  <td></td>
						                  <td>Média</td>			                  
										  <td><%= @media %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td>Nota mais alta</td>			                  
										  <td><%= @max %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td>Nota mais baixa</td>			                  
										  <td><%= @min %></td>
										</tr>
																				
										<tr>
						                  <td></td>
						                  <td>Notas negativas</td>			                  
										  <td><%= @poss %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td>Notas positivas</td>			                  
										  <td><%= @negs %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td>Exercícios resolvidos</td>			                  
										  <td><%= @cmp %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td>Exercicios por resolver</td>			                  
										  <td><%= @inc %></td>
										</tr>
										
										
										<tr>
						                  <td></td>
						                  <td>Melhor disciplina (média)</td>			                  
										  <td><%= @best %></td>
										</tr>
										
										<tr>
						                  <td></td>
						                  <td>Pior disciplina(média)</td>			                  
										  <td><%= @worst %></td>
										</tr>
										
										 
										 
										 
						              </tbody>
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>
 

<div class="links"> 
   <br><br>
  <h5>
    <%= link_to "Voltar", statistics_index_alunos_path  %>
  <h5>
</div>

Applicação/TePeCe/app/views/alunos/statistics_index.html.erb
<h1></h1>
<legend>Estatisticas dos Alunos</legend>

<%= will_paginate %>

<div class="span9" id="content">
                    <div class="row-fluid">
                        <!-- block -->
                        <div class="block">
                            
                            <div class="block-content collapse in">
                                <div class="span12">
  									<table class="table">
						              <thead>									
										<tr>
						                  <th>#</th>
						                  <th>Nome</th>
						                  <th></th>
						                  <th></th>
						                </tr>
						              </thead>
						              
									  
									  
									  <tbody>
									   <% @alunos.each do |aluno| %>
						                <tr>
						                  <td><%= aluno.id %></td>
						                  <td><%= link_to aluno.nome, aluno %></td>
						                 
						                  
										  <% if current_user.admin? %>
										  <td><%= link_to image_tag("search-icon24.png") + 'Consultar estatisticas', aluno_statistics_path(aluno) %></td>
										  <% end %>
										</tr>
										 <% end %>
						              </tbody>
						            </table>
                                </div>
                            </div>
                        </div>
                        <!-- /block -->
					</div>
</div>


<%= will_paginate %>

Applicação/TePeCe/app/views/alunos/stats_byturma.html.erb
<h1></h1>
<legend>Estatisticas de alunos da Turma <%= @turma.designacao %></legend>


<%= will_paginate %>

<ul class="alunos">
	<% @alunos.each do |aluno| %>
	<li>
		<b><%= aluno.nome %> </b>
		<div>
			<td><%= link_to 'Consultar estatisticas', aluno_statistics_path(aluno) %></td>
		</div>
    </li>
	
  <% end %>
</ul>

<%= will_paginate %>

<%= link_to 'Voltar', statistics_index_turmas_path %>