Applicação/TePeCe/config/routes.rb
Rails.application.routes.draw do

  resources :turmas do
    get 'statistics'
    collection do
      get 'statistics_index'
    end
  end

  resources :disciplinas

  resources :exercicios do
    resources :resolucaos
    resources :nota
    collection do
      get 'bydisc/:disciplina_id' => 'exercicios#bydisc', :as => "bydisc"
    end
  end

  resources :encarregados

  resources :profs

  resources :alunos do
    get 'statistics'
    collection do
      get 'statistics_index'
      get 'statistics_index/byturma/:turma_id' => 'alunos#stats_byturma', :as => "stats_byturma"
      get 'byturma/:turma_id' => 'alunos#byturma', :as => "byturma"
    end
  end

  resources :direcs

	resources :sessions, only: [:new, :create, :destroy]
  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/statistics'

  resources :users do
    resources :mensagens
  end

  root 'static_pages#home'
  
	match '/signup',  to: 'users#new',            via: 'get'
	match '/signin',  to: 'sessions#new',         via: 'get'
	match '/signout', to: 'sessions#destroy',     via: 'delete'

end

Applicação/TePeCe/app/models/aluno.rb
class Aluno < ActiveRecord::Base
	belongs_to :user
	has_many :exercios
	has_many :notas
	belongs_to :turma
	belongs_to :encarregado
	
	
	
end

Applicação/TePeCe/app/models/direc.rb
class Direc < ActiveRecord::Base
end

Applicação/TePeCe/app/models/disciplina.rb
class Disciplina < ActiveRecord::Base
	has_many :exercicios
end

Applicação/TePeCe/app/models/encarregado.rb
class Encarregado < ActiveRecord::Base
	has_many :alunos
end

Applicação/TePeCe/app/models/exercicio.rb
class Exercicio < ActiveRecord::Base
	belongs_to :aluno
	has_one :resolucao
	has_one :nota
	has_one :disciplina
	belongs_to :prof
end

Applicação/TePeCe/app/models/mensagen.rb
class Mensagen < ActiveRecord::Base
	belongs_to :destino, class_name: 'User', foreign_key: 'destinatario'
	belongs_to :origem, class_name: 'User', foreign_key: 'remetente'
end

Applicação/TePeCe/app/models/nota.rb
class Nota < ActiveRecord::Base
	belongs_to :exercicio
	belongs_to :aluno
end

Applicação/TePeCe/app/models/prof.rb
class Prof < ActiveRecord::Base
	has_many :exercicios
end

Applicação/TePeCe/app/models/resolucao.rb
class Resolucao < ActiveRecord::Base
	belongs_to :exercicio
end

Applicação/TePeCe/app/models/turma.rb
class Turma < ActiveRecord::Base
	has_many :alunos
end

Applicação/TePeCe/app/models/user.rb
class User < ActiveRecord::Base
	has_one :aluno, dependent: :destroy
	has_one :prof
	has_one :direc
	has_one :encarregado
	
	has_many :mensagens
	
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
				format: { with: VALID_EMAIL_REGEX },
				length: { maximum: 50 },
				uniqueness: true
	has_secure_password			
	validates :password, length: { minimum: 6 }
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.digest(token)
		Digest::SHA1.hexdigest(token.to_s)
	end
	
	def user_name
		if self.aluno
			self.aluno.nome
		elsif self.prof
			self.prof.nome
		elsif self.direc
			self.direc.nome
		else
			self.encarregado.nome
		end	
	end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
	
end

Applicação/TePeCe/app/controllers/resolucaos_controller.rb
class ResolucaosController < ApplicationController
  before_action :set_resolucao, only: [:show, :edit, :update, :destroy]

  # GET /resolucaos
  # GET /resolucaos.json
  def index
    @resolucaos = Resolucao.all
  end

  # GET /resolucaos/1
  # GET /resolucaos/1.json
  def show
  end

  # GET /resolucaos/new
  def new
    @exercicio = Exercicio.find(params[:exercicio_id])
    @resolucao = Resolucao.new
    @resolucao.exercicio = @exercicio
  end

  # GET /resolucaos/1/edit
  def edit
  end

  # POST /resolucaos
  # POST /resolucaos.json
  def create
    @resolucao = Resolucao.new(resolucao_params)
    @exercicio = Exercicio.find(@resolucao.exercicio_id)
    respond_to do |format|
      if @resolucao.save and exercicio.save
        format.html { redirect_to @exercicio, notice: 'Resolucao was successfully created.' }
        format.json { render :show, status: :created, location: @resolucao }
      else
        format.html { render :new }
        format.json { render json: @resolucao.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resolucaos/1
  # PATCH/PUT /resolucaos/1.json
  def update
    respond_to do |format|
      if @resolucao.update(resolucao_params)
        format.html { redirect_to @exercicio, notice: 'Resolucao was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercicio }
      else
        format.html { render :edit }
        format.json { render json: @resolucao.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resolucaos/1
  # DELETE /resolucaos/1.json
  def destroy
    @resolucao.destroy
    respond_to do |format|
      format.html { redirect_to resolucaos_url, notice: 'Resolucao was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resolucao
      @exercicio = Exercicio.find(params[:exercicio_id])
      @resolucao = Resolucao.find_by_exercicio_id(params[:exercicio_id])
      if @resolucao == nil
        @resolucao = Resolucao.new
        @resolucao.exercicio = @exercicio
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resolucao_params
      params.require(:resolucao).permit(:resposta, :exercicio_id)
    end
end

Applicação/TePeCe/app/helpers/alunos_helper.rb
module AlunosHelper
end

Applicação/TePeCe/app/helpers/application_helper.rb
module ApplicationHelper
end

Applicação/TePeCe/app/helpers/direcs_helper.rb
module DirecsHelper
end

Applicação/TePeCe/app/helpers/exercicios_helper.rb
module ExerciciosHelper
end

Applicação/TePeCe/app/helpers/mensagens_helper.rb
module MensagensHelper
end

Applicação/TePeCe/app/helpers/nota_helper.rb
module NotaHelper
end

Applicação/TePeCe/app/helpers/profs_helper.rb
module ProfsHelper
end

Applicação/TePeCe/app/helpers/resolucaos_helper.rb
module ResolucaosHelper
end

Applicação/TePeCe/app/helpers/sessions_helper.rb
module SessionsHelper
	def sign_in(user)
		remember_token = User.new_remember_token
		cookies.permanent[:remember_token] = remember_token
		user.update_attribute(:remember_token, User.digest(remember_token))
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end
	
	def current_user=(user)
		@current_user = user
	end
	
	def current_user
		remember_token = User.digest(cookies[:remember_token])
		@current_user ||= User.find_by(remember_token: remember_token)
	end

	def current_user?(user)
		user == current_user
	end
	
	def sign_out
		current_user.update_attribute(:remember_token,
                                  User.digest(User.new_remember_token))
		cookies.delete(:remember_token)
		self.current_user = nil
	end
	
	def redirect_back_or(default)
		redirect_to(session[:return_to] || default)
		session.delete(:return_to)
	end

	def store_location
		session[:return_to] = request.url if request.get?
	end
end

Applicação/TePeCe/app/helpers/turmas_helper.rb
module TurmasHelper
end

Applicação/TePeCe/app/helpers/users_helper.rb
module UsersHelper
end

Applicação/TePeCe/app/views/resolucaos/_form.html.erb
<%= form_for @resolucao, url: new_exercicio_resolucao_path(@exercicio), html: { method: :put } do |f| %>
  <% if @resolucao.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resolucao.errors.count, "error") %> prohibited this resolucao from being saved:</h2>

      <ul>
      <% @resolucao.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label "Enunciado" %><br>
    <%= f.label @exercicio.enunciado %><br>
  </div>
  
  <div class="field">
    <%= f.label :resposta %><br>
    <%= f.text_area :resposta %>
  </div>
  
  <div class="actions">
    <%= f.submit "Gravar" %>
  </div>
<% end %>

Applicação/TePeCe/app/views/resolucaos/edit.html.erb
<h1>Editing resolucao</h1>

<%= render 'form' %>

<%= link_to 'Voltar', exercicio_path(@exercicio) %>

Applicação/TePeCe/app/views/resolucaos/index.html.erb
<h1>Listing resolucaos</h1>

<table>
  <thead>
    <tr>
      <th>Resposta</th>
      <th>Exercicio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resolucaos.each do |resolucao| %>
      <tr>
        <td><%= resolucao.resposta %></td>
        <td><%= resolucao.exercicio_id %></td>
        <td><%= link_to 'Ver', resolucao %></td>
        <td><%= link_to 'Alterar', edit_resolucao_path(resolucao) %></td>
        <td><%= link_to 'Apagar', resolucao, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Applicação/TePeCe/app/views/resolucaos/new.html.erb
<h1>New resolucao</h1>

<%= render 'form' %>

<%= link_to 'Voltar', exercicio_path(@exercicio) %>

Applicação/TePeCe/app/views/resolucaos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resposta:</strong>
  <%= @resolucao.resposta %>
</p>

<p>
  <strong>Exercicio:</strong>
  <%= @resolucao.exercicio_id %>
</p>

<%= link_to 'Alterar', edit_resolucao_path(@resolucao) %> |
<%= link_to 'Voltar', resolucaos_path %>